Add gocardless support for Berliner Sparkasse (Germany)
actualbudget/actual-server pull request #358
Opened 2024-05-16 21:02 UTC by Peccadilloz

Similar to PR #346 this adds a gocardless formatter to properly format transaction information. The additional remittance information was not picked up by actual as this bank transmits it as remittanceInformationStructured instead of remittanceInformationUnstructured. 

I have tested this successfully with my bank. The "Notes" section is now being filled with the additional remittance information.

This fixes my original issue in the actual repo  [#2759](https://github.com/actualbudget/actual/issues/2759)

2024-05-25 16:45 UTC, psybers requested changes

2024-05-25 16:45 UTC, psybers commented on src/app-gocardless/banks/berliner_sparkasse_beladebexxx.js
> +    return sortByBookingDateOrValueDate(transactions);
This seems like the default case.  Could you import and use the fallback version instead?

See this file for an example: https://github.com/actualbudget/actual-server/blob/master/src/app-gocardless/banks/belfius_gkccbebb.js

2024-05-25 16:53 UTC, psybers requested changes
Can you add a test case?  See https://github.com/actualbudget/actual-server/blob/master/src/app-gocardless/banks/tests/belfius_gkccbebb.spec.js for an example.

2024-06-01 04:01 UTC, psybers commented
Be sure to update this file too: https://github.com/actualbudget/actual-server/blob/master/src/app-gocardless/tests/bank-factory.spec.js

2024-06-01 05:16 UTC, psybers commented
Actually hold off on modifying the test for bank factory. #367 should make that no longer necessary.

2024-07-11 16:24 UTC, Peccadilloz commented
Sorry for being inactive this last month. I'll be back home this weekend and will pick this up.

2024-08-03 06:30 UTC, Peccadilloz commented
> Thanks for working on this! Would you mind updating the PR to use prop spreading for `Fallback`? Here's an example bank provider:
> 
> https://github.com/actualbudget/actual-server/blob/aa22e6951dd90fc03e086593f001d0a002b6e324/src/app-gocardless/banks/american-express-aesudef1.js#L7
> 
> We recently merged some changes to simplify them.
> 
> Happy to merge this PR once that's done + the conflict is solved!

I have updated this PR to include the requested changes and resolved the mentioned conflict. Any chance this can be included in the upcoming update still? 
Best regards! 
Peccadilloz

2024-08-03 16:00 UTC, MatissJanis approved these changes
Thanks!

You'll be able to use this change via the next `edge` tag (tomorrow). Sorry for not getting it in the current release. It barely missed the cut.

2024-08-03 16:00 UTC, merged

2024-08-03 22:10 UTC, Peccadilloz commented
> Thanks!
> 
> You'll be able to use this change via the next `edge` tag (tomorrow). Sorry for not getting it in the current release. It barely missed the cut.

No worries, I knew I was late for the release. 
Thanks for the quick merge!

2024-08-09 12:59 UTC, tennox commented
@Peccadilloz do you think I can just add the IDfor Mittelbrandenburgische Sparkasse and it'll work? 🤔
I'm also missing the remittance information as a note

2024-08-13 20:39 UTC, DirgoSalga commented
I am also having the same trouble with my bank. It is the Rheinhessen Sparkasse (that is the official name), the name under GoCardless was: Sparkasse Worms-Alzey-Ried (BIC: MALADE51WOR).