Grab payee name for Abanca gocardless integration
actualbudget/actual-server pull request #359
Opened 2024-05-18 10:09 UTC by daca11

Current GoCardless integration with Abanca is not able to get Payee name because `creditorName` and `debtorName` are empty.
That information is actually in the `remittanceInformationStructured`. This fix adds that information to `creditorName` and `debtorName` so the payee name is correctly imported into the transaction correctly.

2024-05-25 16:54 UTC, psybers requested changes
Can you add a test case? See https://github.com/actualbudget/actual-server/blob/master/src/app-gocardless/banks/tests/belfius_gkccbebb.spec.js for an example.

2024-06-01 04:01 UTC, psybers commented
Be sure to update this file too: https://github.com/actualbudget/actual-server/blob/master/src/app-gocardless/tests/bank-factory.spec.js

2024-06-01 05:16 UTC, psybers commented
Actually hold off on modifying the test for bank factory. #367 should make that no longer necessary.

2024-06-07 18:49 UTC, MatissJanis commented
Thanks for working on this! Would you mind updating the PR to use prop spreading for `Fallback`? Here's an example bank provider: https://github.com/actualbudget/actual-server/blob/aa22e6951dd90fc03e086593f001d0a002b6e324/src/app-gocardless/banks/american-express-aesudef1.js#L7

We recently merged some changes to simplify them.

Happy to merge this PR once that's done + the conflict is solved!

2024-06-08 08:28 UTC, daca11 commented
Added a test and the ...Fallback line.
Sorry for the trial-and-error commits, as a DevOps I never worked with ts. I hope the test is correct, I just based my work on the existing files 😄

2024-06-08 12:38 UTC, MatissJanis requested changes

2024-06-08 12:38 UTC, MatissJanis commented on src/app-gocardless/banks/abanca-caglesmm.js
> +  },
Can remove these. The prop spreading on line 5 takes care of adding them.

```suggestion
```

2024-06-08 12:38 UTC, MatissJanis commented on src/app-gocardless/banks/abanca-caglesmm.js
> +
```suggestion
```

2024-06-08 13:08 UTC, MatissJanis approved these changes
Thanks!

2024-06-08 13:09 UTC, merged