Update docker-compose.yml
actualbudget/actual-server pull request #416
Opened 2024-08-09 16:54 UTC by latetedemelon

Added all known options (known to me anyway)

2024-08-14 05:05 UTC, psybers requested changes

2024-08-14 05:05 UTC, psybers commented on docker-compose.yml
>        # - ACTUAL_PORT=5006
I wonder if this should have a comment pointing out that if you change it from 5006, you need to update line 8 to match?

2024-08-14 05:05 UTC, psybers commented
Don't forget a release note.

2024-08-15 12:41 UTC, tcrasset commented on docker-compose.yml
> +    ## Common tags: latest, edge (ADVANCED ONLY), lastest-alpine, edge-alpine (ADVANCED ONLY), specific version (e.g. 24.8.0, 24.8.0-alpine)
```suggestion
    ## Common tags: latest, edge (ADVANCED ONLY), latest-alpine, edge-alpine (ADVANCED ONLY), specific version (e.g. 24.8.0, 24.8.0-alpine)
```
Typo

2024-08-28 02:27 UTC, closed without merging