integrate FileService for app-sync.js
actualbudget/actual-server pull request #432
Opened 2024-08-16 22:47 UTC by tcrasset

- **add FileService and tests**
- **add find() to FilesService**
- **Add integration tests for remaining app-sync.js endpoints%**
- **use filesService in /get-user-file-info**
- **integrate FilesService  for /list-user-files**
- **integrate FilesService for /update-user-filename**
- **verify file exists in function**
- **integrate FilesService for /download-user-file**
- **integrate FilesService for /reset-user-file**
- **integrate FilesService for /user-create-key**
- **integrate FilesService for /user-get-key**
- **integrate FilesService for /delete-user-file**

2024-09-10 19:47 UTC, matt-fidd commented
Thanks for this! I'm looking to have it fully reviewed this week, sorry it's taken a little while.
One of the tests is failing, please could you have a look?

2024-09-11 08:58 UTC, tcrasset commented
> Thanks for this! I'm looking to have it fully reviewed this week, sorry it's taken a little while. One of the tests is failing, please could you have a look?

Hey, thanks!
The test is flaky. Manual testing revealed that it's because we're not handling the database state correctly across the app. When all tests run in parallel across all the services, something goes wrong in the `accountDb`, and makes the test fail because the database couldn't be updated. Not only this test is affected, but other tests in `app-sync.test.js` as well. If I only run the `app-sync.test.js` tests, it never fails. It's only when they are run in parallel with the whole test suite. I haven't been able to pinpoint the exact problem. 


The current usage (one user per server) may make this a non-issue in production, but I think on a multi user system, with lots of calls, the database will be an issue.

2024-09-18 16:52 UTC, matt-fidd commented
Looking at this now

Just out of interest...

@coderabbitai review

2024-09-18 16:55 UTC, MikesGlitch commented
@coderabbitai review

2024-09-18 17:11 UTC, matt-fidd requested changes
Sorry this has taken so long to get a review in.
Two little nits.

2024-09-18 17:11 UTC, matt-fidd commented on src/app-sync.js
> +function boolToInt(deleted) {
nit: could these function definitions be moved to the top please? `verifyFileExists` and `boolToInt`

2024-09-18 17:11 UTC, matt-fidd commented on src/app-sync.js
> +app.use(errorMiddleware);
This is already added in line 28

2024-10-23 08:56 UTC, matt-fidd approved these changes
Thank you for this, massive improvement 🎉

2024-10-23 09:03 UTC, merged