🧹 Optimise GoCardless bank sync to use fewer api calls
actualbudget/actual-server pull request #436
Opened 2024-08-17 16:10 UTC by matt-fidd

Depends on merge of #435 

Part of #431 
Complimentary to PR in actual: actualbudget/actual#3279

The balance fetched from gocardless is used to calculate the starting balance, which is only relevant when a completely blank account is synced. This change lays the groundwork in the server to allow the client side to be more selective in what it retrieves.

2024-08-17 16:37 UTC, psybers requested changes

2024-08-17 16:37 UTC, psybers commented on src/app-gocardless/services/gocardless-service.js
> +
Can we refactor this out into a shared method to avoid the duplication with the other function?  That way there is less chance of divergence.

2024-08-17 18:36 UTC, psybers approved these changes

2024-08-25 20:53 UTC, MikesGlitch approved these changes

2024-08-26 10:03 UTC, merged