Fix 'Out of sync' error
actualbudget/actual-server pull request #52
Opened 2022-05-29 19:58 UTC by 7brend7

When I've tried to modify some account (add a transaction) on **second** computer, I've got "Your data is out of sync" error on first.

![image](https://user-images.githubusercontent.com/2050897/170888766-576b3ee1-a228-4358-ad7d-fcd6809dd05d.png)

This PR should fix sync error message.

NOT Done:
- handle the encryptKeyId  for encrypted messages;

2022-05-30 20:34 UTC, bjornbostrom commented
I have tried the 7brend7:fix-out-of-sync branch with some scenarios regarding accessing my budget files on several computers that did not work with the master branch. It seems to work perfectly OK 👍

2022-05-30 22:33 UTC, bosmak commented
It did fix the out-of-sync issue, but it creates some weird behaviors when using two or more files as they all become a merged copy of themselves.


[![actualbudget-issue.gif](https://s8.gifyu.com/images/actualbudget-issue.gif)](https://gifyu.com/image/SxZJg)

2022-05-31 05:45 UTC, bjornbostrom commented
@bosmak: strange, when I tested yesterday I was actually testing it with two budgetfiles, and it all seems to work very smooth. When you had the weired behaivours, was it before @jlongster pushed the [Fix CORS issues](https://github.com/actualbudget/actual-server/commit/a2a460a8834517c50657a01e8f37997a3b2188a3) 2 days ago (hash a2a460a8834517c50657a01e8f37997a3b2188a3) ? The [Fix CORS issues](https://github.com/actualbudget/actual-server/commit/a2a460a8834517c50657a01e8f37997a3b2188a3) together with your PR might solve the problem altogether...?

2022-05-31 17:12 UTC, bjornbostrom commented
Strange... I also totally wiped the contents of the data-dir and uploaded  new fresh exported .zip's from the closed-source site. Did you also clean the data-dir? (just trying to figure out why it seems to work here...)

2022-05-31 17:19 UTC, bosmak commented
Yeah, I'm running on docker, So I built the new image and changed the mount points to a new folder to start a clean install.

2022-05-31 19:33 UTC, bosmak commented
@7brend7 @bjornbostrom I did some more testing, so what I found is, If I access from the localhost, it seems to work correctly, but when I use the IP, it does this strange behavior; in my case, I'm accessing the server on a different machine from the one hosting it.

So using `localhost` or `127.0.0.1` works without issue, but it happens as soon as I use `192.168.1.188`.

https://gifyu.com/image/SxrtG

2022-05-31 21:09 UTC, bjornbostrom commented
@bosmak I see, my setup is a virtual Rocky Linux 8.6 running docker and NGINX acting as a reverse proxy. So in my case, I am actually not browsing the docker-instance directly on port 5006. Rather I am browsing to https://my.server.com. The config in NGINX is 
`proxy_pass http://127.0.0.1:5006/;`

So I guess behind the scenes, NGINX is connecting to actual on localhost/127.0.0.1. 

Can that be the reason it works in my case then?

2022-05-31 21:55 UTC, bosmak commented
@bjornbostrom Interesting, I tried to replicate your NGINX reverse proxy setup, but no luck there.

But If I use a Cloudflare tunnel to access it externally it works correctly, with no issues and I can see they aren't duplicating anymore.

P.S. once a file was been "duplicated" it gets buggy as well, the name of the file is kept the same across all files, so I had to delete everything and start from scratch.

2022-05-31 22:25 UTC, bjornbostrom commented
Yep, I'm using https on my nginx.

2022-06-01 14:24 UTC, jlongster commented
@bosmak Whatever you have sitting in front of your server, it is dropping headers. You need to be sure that it is responding with these headers to enable `SharedArrayBuffer`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements

I'm going to be working on removing the "fallback" mode of browser storage because it's buggy. When this happens, the app will simply not work if `SharedArrayBuffer` is enabled so it will be more clear when this happens

2022-06-01 14:38 UTC, jlongster requested changes
Oh man, can't believe I didn't catch this 🤦 

Thanks so much for figuring this out! We definitely need to fix this to fix syncing across multiple devices. Dang, syncing should be robust but I missed some of this stuff when open-sourcing. At the core syncing is robust, but we just gotta make the server send back the right messages.

Let's move around the code a little bit. Thanks again!

2022-06-01 14:38 UTC, jlongster commented on app-sync.js
> +    envelopePb.setContent(messagePb.serializeBinary());
To support the `sync-simple.js` use case, where that flow that stores the binary-encoded messages directly, let's move encoding the messages into `sync-full.js`. `newMessages` should be an array of message envelopes, so the loop just becomes:

```
  for (let msg of newMessages) {
    responsePb.addMessages(msg);
  }
```

We'll also need to update the `sync-simple.js` flow to encode the messages, but I can do that

2022-06-03 02:58 UTC, jlongster commented
@7brend7 thanks for the changes; do you see the option in the right sidebar to "allow edits from maintainers"? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

If so is it checked? I'm trying to figure out why I can push changes to PRs

2022-06-03 06:45 UTC, 7brend7 commented
@jlongster yep... it's checked... feel free to push any changes )

2022-06-10 14:30 UTC, sdrichter commented
FYI - You can recover from this issue by exporting your budget in Actual, then reimporting it on the patched version of the server. This restores all your accounts, transactions, etc. and the syncing issue does not come along with the imported data.

2022-06-15 00:37 UTC, sdrichter commented
FYI - No idea how I did it, but even running this PR on my server, my budget has somehow entered the syncing error state again and I can't get it to recover. So this patch doesn't seem to be foolproof.

2022-06-15 00:39 UTC, bosmak commented
@sdrichter do you have HTTPS configured? I always have the issue if I'm not using HTTPS

2022-06-15 12:20 UTC, sdrichter commented
I am using actual-server via Docker-Compose and running behind a Traefik reverse proxy. The actual-server instance itself is only running HTTP but I access it via HTTPS through the reverse proxy.

2022-06-17 13:45 UTC, kinwolfqc commented
I applied the PR last week, but today I got the sync error again, so, like @sdrichter , I can report that the problem is still there with the PR, it happens less often though.

2022-06-26 21:31 UTC, jlongster commented
Sorry about this! Finally going through PRs and this is the first one I'm merging because it fixes a critical problem.

I made a slight change to keep the changes small, but after talking with people we probably should start using `const` and not mutating variables to make it easier to use TypeScript.  I like using `let` everywhere, but that will be harder with TypeScript.

2022-06-26 21:31 UTC, merged